Repository WGBH-MLA/chowda, pull requests merged in 2023-05, with the labels that each got.

#31 🖊 Fix Doc Typo
  docs/install.md
  main.py
Labels: bug :bug:, documentation :scroll:

#33 Inherit
  .github/workflows/CI.yml
  chowda/app.py
Labels: bug :bug:, test ⚗️

#34 ©️ SonyCi
  pdm.lock
  pyproject.toml
  tests/factories.py
Labels: CD :building_construction:

#35 🛌 Fixes Coverage
  .coveragerc
  pyproject.toml
  tests/__init__.py
  tests/seeds.py
  tests/test_factories.py
Labels: CI :test_tube:, bug :bug:

#40 📌 Pins urllib3 to ~= 1.26
  pdm.lock
  pyproject.toml
Labels: bug :bug:, test ⚗️

#39 📓 Notebook tests
  .github/workflows/CI.yml
  .vscode/launch.json
  chowda/__init__.py
  docs/examples/session.ipynb
  pdm.lock
  pyproject.toml
  tests/test_app.py
Labels: CI :test_tube:, documentation :scroll:, test ⚗️

#41 📛 ClamsApp name
  chowda/models.py
Labels: enhancement :heavy_plus_sign:

#42 Updates Collection and Batch list view
  chowda/app.py
  chowda/views.py
Labels: enhancement :heavy_plus_sign:

#45 🕸 Debug
  Dockerfile
  chowda/config.py
  chowda/db.py
Labels: bug :bug:

#46 📼 VCR.py
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  chowda/models.py
  pdm.lock
  pyproject.toml
  tests/ci.test.toml
  tests/conftest.py
Labels: dev 💻, test ⚗️
