Repository WGBH-MLA/chowda, pull requests merged in 2023-08, with the labels that each got.

#94 🔄 Connect Sync button
  chowda/app.py
  chowda/auth/oauth.py
  chowda/routers/__init__.py
  chowda/routers/dashboard.py
  chowda/views.py
  templates/dashboard.html
  tests/test_app.py
Labels: bug :bug:, enhancement :heavy_plus_sign:

#96 🌄 `mmif_json` view
  chowda/views.py
Labels: enhancement :heavy_plus_sign:

#101 🏓 Batch: tabler class
  templates/forms/media_files.html
Labels: bug :bug:

#106 🛡 Protect sync button
  chowda/views.py
  templates/dashboard.html
Labels: enhancement :heavy_plus_sign:

#110 🔢 `media_file_count`
  chowda/views.py
Labels: bug :bug:

#113 🔐 Auth permissions
  chowda/views.py
Labels: enhancement :heavy_plus_sign:

#119 114 fix batch save
  chowda/utils.py
  chowda/views.py
  pdm.lock
  pyproject.toml
  templates/forms/media_files.html
  tests/test_batches.py
Labels: bug 🐛

#121 Adds 'Duplicate' and 'Combine' actions for Batches.
  chowda/views.py
Labels: enhancement ➕

#122 🙈 Hides GUIDs from list views
  chowda/views.py
Labels: enhancement ➕

#123 📑 Tabular display of related `MediaFiles`
  chowda/views.py
  templates/displays/batch_media_files.html
  templates/displays/collection_media_files.html
  templates/displays/media_files.html
  templates/forms/media_file_guids_textarea.html
Labels: enhancement ➕, maintenance 🔧

#125 🧮 Fixes `MediaFileCount` field
  chowda/views.py
Labels: bug 🐛

#127 🔗 Fixes `media_file` links
  templates/displays/batch_media_files.html
  templates/displays/collection_media_files.html
Labels: bug 🐛

#132 🧑‍🍳️ Create Batch from Collection
  chowda/views.py
Labels: enhancement ➕

#130 ⬇️ Batch default sort
  chowda/fields.py
  chowda/views.py
Labels: enhancement ➕, maintenance 🔧

#134 🦇 Batch status
  chowda/app.py
  chowda/fields.py
  chowda/models.py
  chowda/utils.py
  chowda/views.py
  migrations/versions/3ae9e767f652_initial_chowda_db_schema.py
  templates/displays/batch_media_files.html
  templates/displays/media_file_count.html
  tests/factories.py
  tests/locustfile.py
  tests/seeds.py
  tests/test_app.py
  tests/test_factories.py
Labels: enhancement ➕, breaking 💔

#133 🍄 Mario Pipelines
  chowda/views.py
Labels: enhancement ➕

#135 👍 Sony Ci Asset Thumbnails
  chowda/fields.py
  chowda/models.py
  chowda/views.py
  static/js/custom_render.js
  templates/displays/sony_ci_asset_thumbnail.html
Labels: enhancement ➕

#138 🛡 GitGuardian
  README.md
  pre-commit-config.yml
Labels: dev 💻
