Repository WGBH-MLA/chowda, pull requests merged in 2023-04, with the labels that each got.

#15 📦 PDM
  .dockerignore
  .github/workflows/docs.yml
  .gitignore
  Dockerfile
  chowda/_version.py
  docs/index.md
  pdm.lock
  poetry.lock
  poetry.toml
  pyproject.toml
Labels: maintenance :wrench:

#17 ⚙️ VSCode pytest settings
  .vscode/settings.json
Labels: dev 💻

#18 👲 `factory_boy`: relational data
  .gitignore
  chowda/models.py
  pdm.lock
  pyproject.toml
  tests/factories.py
  tests/test_factories.py
Labels: test ⚗️

#21 🌱 Seed
  .github/workflows/CI.yml
  .gitignore
  chowda/config.py
  chowda/db.py
  chowda/models.py
  pdm.lock
  pyproject.toml
  tests/conftest.py
  tests/factories.py
  tests/seeds.py
  tests/test_factories.py
Labels: maintenance :wrench:, dev 💻

#20 👚 Update workflow
  .github/workflows/update.yml
Labels: CD :building_construction:, maintenance :wrench:

#24 🔆 Tweaks to display fields, seeds
  chowda/models.py
  tests/factories.py
  tests/seeds.py
Labels: enhancement :heavy_plus_sign:, test ⚗️

#26 🏺 CollectionView
  chowda/admin.py
  chowda/app.py
  chowda/config.py
  chowda/db.py
  chowda/views.py
  pdm.lock
  pyproject.toml
  static/js/custom_render.js
  templates/displays/media_file_guid_links.html
Labels: enhancement :heavy_plus_sign:

#27 🥼 New lint rules
  pyproject.toml
  tests/factories.py
  tests/seeds.py
Labels: maintenance :wrench:

#28 ✋ Unignore ruff rules
  .gitignore
  chowda/__init__.py
  chowda/db.py
  chowda/models.py
  chowda/views.py
  pdm.toml
  pyproject.toml
  tests/factories.py
  tests/locustfile.py
  tests/seeds.py
  tests/test_factories.py
Labels: maintenance :wrench:

#29 Install Docs
  README.md
  chowda/README.md
  docs/examples/session.ipynb
  docs/index.md
  docs/install.md
  docs/reference/index.md
  mkdocs.yml
  overrides/main.html
  pdm.lock
  pyproject.toml
Labels: documentation :scroll:
