Repository WGBH-MLA/chowda, pull requests merged in 2023-03, with the labels that each got.

#1 Sets Docker compose for dev server and tests
  .gitignore
  Dockerfile
  chowda/__init__.py
  docker-compose.yml
  main.py
Labels: enhancement :heavy_plus_sign:, dev 💻

#2 🌟 starlette-admin
  .github/workflows/CD.yml
  Dockerfile
  README.md
  chowda/__init__.py
  chowda/app.py
  chowda/config.py
  chowda/models.py
  chowda/views.py
  poetry.lock
  poetry.toml
  pyproject.toml
  requirements.txt
Labels: CD :building_construction:, enhancement :heavy_plus_sign:, dev 💻

#3 💻 VSCode
  .vscode/launch.json
Labels: dev 💻

#4 🗿 Initial Models
  .gitignore
  chowda/__init__.py
  chowda/_version.py
  chowda/app.py
  chowda/config.py
  chowda/models.py
  chowda/views.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
Labels: enhancement :heavy_plus_sign:

#5 🧪 Tests
  .coveragerc
  .flake8
  .github/workflows/CI.yml
  .vscode/launch.json
  README.md
  chowda/README.md
  codecov.yml
  poetry.lock
  pyproject.toml
  tests/test_app.py
Labels: CI :test_tube:

#6 📚 Docs
  .github/workflows/docs.yml
  chowda/app.py
  chowda/models.py
  docs/index.md
  docs/reference/app.md
  docs/reference/models.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation :scroll:

#7 🪳 Locust
  tests/locustfile.py
Labels: test ⚗️

#9 🐙 Release
  .github/workflows/release.yml
Labels: CD :building_construction:

#10 🐋 Docker tests
  Dockerfile
  requirements-test.txt
Labels: test ⚗️

#11 🏋 Load testing
  chowda/config.py
  chowda/db.py
  tests/locustfile.py
Labels: test ⚗️

#12 🤪 Psycopg
  .github/workflows/CD.yml
  Dockerfile
  chowda/db.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
Labels: production 🎭
