Repository WGBH-MLA/chowda, pull requests merged in 2023-07, with the labels that each got.

#62 👣 Migration tool
  .env.development
  .env.test
  .vscode/settings.json
  Dockerfile
  alembic.ini
  chowda/_version.py
  chowda/admin.py
  chowda/app.py
  chowda/config.py
  chowda/db.py
  chowda/models.py
  chowda/views.py
  docs/examples/__init__.py
  docs/examples/session.ipynb
  docs/install.md
  docs/reference/database.md
  migrations/README
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/d10392cd5788_init_db.py
  pdm.lock
  pyproject.toml
  tests/conftest.py
Labels: enhancement :heavy_plus_sign:

#72 ❎ Removes dotenv override
  chowda/config.py
Labels: production 🎭

#77 🐋 Dockerfile migrations
  .github/workflows/CI.yml
  Dockerfile
  tests/conftest.py
Labels: CD :building_construction:, CI :test_tube:, bug :bug:

#36 🍝 SonyCiAsset
  .github/workflows/CI.yml
  .gitignore
  .vscode/settings.json
  chowda/app.py
  chowda/config.py
  chowda/models.py
  chowda/views.py
  migrations/versions/9a6ec8c9597c_sonyci_assets.py
  pyproject.toml
  tests/factories.py
Labels: documentation :scroll:, enhancement :heavy_plus_sign:

#78 🏄 Initial Dashboard page
  chowda/app.py
  chowda/views.py
  templates/dashboard.html
Labels: enhancement :heavy_plus_sign:

#57 🚰 Metaflow ingest
  .flake8
  .gitignore
  chowda/flows/__init__.py
  chowda/flows/ingest.py
  chowda/log.py
  chowda/utils.py
  docs/examples/upsert.ipynb
  pdm.lock
  pyproject.toml
Labels: enhancement :heavy_plus_sign:

#80 🔄 Sync Event
  chowda/_version.py
  chowda/flows/ingest.py
  chowda/views.py
  docs/examples/events.ipynb
  pyproject.toml
Labels: enhancement :heavy_plus_sign:, production 🎭

#82 🗒 Batch input from text
  chowda/views.py
  templates/forms/media_files.html
Labels: enhancement :heavy_plus_sign:

#79 📬 POST `/api/sony_ci/sync`
  .env.development
  .env.test
  .gitignore
  .vscode/settings.json
  chowda/api.py
  chowda/app.py
  chowda/routers/__init__.py
  chowda/routers/sony_ci.py
  pdm.lock
  pyproject.toml
  tests/routers/test_sony_ci.py
Labels: enhancement :heavy_plus_sign:

#84 🐦 Mocker
  pdm.lock
  pyproject.toml
Labels: bug :bug:, test ⚗️

#89 🔐 OAuth
  chowda/app.py
  chowda/auth/__init__.py
  chowda/auth/oauth.py
  chowda/config.py
  chowda/views.py
  pdm.lock
  pyproject.toml
Labels: enhancement :heavy_plus_sign:, production 🎭

#86 🔄 Displays sync history in dashboard
  .vscode/launch.json
  chowda/__init__.py
  chowda/config.py
  chowda/views.py
  pdm.lock
  pyproject.toml
  templates/dashboard.html
Labels: enhancement :heavy_plus_sign:
